Add new mlxconfig params to mellanox_fw_update.yaml
Mellanox/switchdev-utils pull request #3
Opened 2020-04-26 12:10 UTC by wmousa

(ESWITCH_HAIRPIN_TOT_BUFFER_SIZE, ESWITCH_HAIRPIN_DESCRIPTORS)

2020-04-27 06:35 UTC, wmousa commented
@adrianchiris @moshe010 please review this

2020-04-28 01:02 UTC, moshe010 commented on templates/firstboot/mellanox_fw_update.yaml
> +                        if key in self.arrayed_mlnx_config.keys():
remove the keys()
if key in self.arrayed_mlnx_config

2020-04-28 01:02 UTC, moshe010 commented on templates/firstboot/mlnx_fw_update.py
> +ARRAY_VALUE_REGEX = r'Array\[(?P<first_index>\d+)\.\.(?P<last_index>\d+)\]'
not for this PR. but in the future we should create the Yaml file automatically from this python script using jinja to render from template. Then you should maintain the script in the yaml file. Again this is not for now, but for future enchantment

2020-04-28 10:13 UTC, adrianchiris requested changes

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                 Make sure to choose only the PCI ends with 0
>  Make sure to choose only the PCI ends with 0

if its a global/per-host parameter it shouldnt matter right ?
also if you run on more than one PF, we are not appying the configuration twice correct?

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +    default: {"*": "17"}
better than a list :)

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mlnx_fw_update.py
> +ARRAY_VALUE_REGEX = r'Array\[(?P<first_index>\d+)\.\.(?P<last_index>\d+)\]'
tbh the script is getting pretty large. if it keeps growing we would need to explore alternatives to just putting it flat in the yaml

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +    description: If "*" is on of the json keys, then its value will set to all indexes
i would reword
`If a single key of "*" is provided, then its value will be set to all indexes`

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +    description: If "*" is on of the json keys, then its value will set to all indexes
i would reword
`If a single key of "*" is provided, then its value will be set to all indexes`

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                def get_device_conf_dict(self, param_name=None):
The flow is a bit convoluted, having `get_device_conf_dict` call `_mstconfig_parse_data` which calls back `get_device_conf_dict`

you could modify get_device_conf_dict to perform a 2 passess on the output. 
1 the normal mlxconfig query
2. expand the array configuration to their elements (you can do that recursively if you prefer using `get_device_conf_dict`)

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                    self.arrayed_mlnx_config = {}
maybe add a comment explaining what this attribute stores/represents ? or better yet just define a class for it (which has first and last index attributes)

also perhaps a better name would be:  `array_config_info`  ?

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                            self.arrayed_mlnx_config[d[0]] = [first_index, last_index]
i prefer not to hide filling up the self.arrayed_mlnx_config in _mst_config_parse_data

can we have a separate method that gets the conf_dict and fills up that information ?

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                            if value.get('*'):
id prefer if you implement the logic to expand the user provided "conf_dict" in a separate method.
also  need to update the docstring for set_config.

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                            if value.get('*'):
need to validate that if "*" is provided, no other entries are in the dict.

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
> +                                             str(param_value).lower() not in \
is there a reason you are using `in` and not `==` ?
e.g  "1" in "100" is true and would then lead to the configuration to be skipped

2020-04-28 10:13 UTC, adrianchiris commented on templates/firstboot/mellanox_fw_update.yaml
>                          ) not in current_mlx_config.get(key).lower():
same issue is here as well i think

2020-04-30 14:38 UTC, adrianchiris commented
@moshe010 @wmousa

2020-04-30 20:50 UTC, moshe010 reviewed
the change is very complex ;(. you probably tested only the script, right?
I guess Waleed will need to test  full deployment ...

2020-04-30 20:50 UTC, moshe010 commented on templates/firstboot/mlnx_fw_update.py
> +        self.mlnx_config_array_param_metadata = dict()
can you make all the code use {} instead of dict() just be consistent

2020-05-03 06:50 UTC, adrianchiris commented on templates/firstboot/mlnx_fw_update.py
> +        self.mlnx_config_array_param_metadata = dict()
sure

2020-05-05 07:17 UTC, adrianchiris reviewed
LGTM

2020-05-05 08:50 UTC, moshe010 approved these changes

2020-05-05 08:50 UTC, merged